# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mes.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tmes.proto\x12\x07grpcmgr\"\x07\n\x05\x45mpty\"\x13\n\x05\x65vent\x12\n\n\x02id\x18\x01 \x01(\t2Z\n\x06MgrApi\x12\'\n\x03var\x12\x0e.grpcmgr.event\x1a\x0e.grpcmgr.event\"\x00\x12\'\n\x03\x66oo\x12\x0e.grpcmgr.Empty\x1a\x0e.grpcmgr.event\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mes_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=22
  _EMPTY._serialized_end=29
  _EVENT._serialized_start=31
  _EVENT._serialized_end=50
  _MGRAPI._serialized_start=52
  _MGRAPI._serialized_end=142
# @@protoc_insertion_point(module_scope)
